### ISSUE TITLE
Keyboard Typing Not Working

### ISSUE THREAD

**Issue by EchoEngineer434** [FlamedDogo99/EaglerMobile#36]
So i'm using an Android, and the problem is That when i open up the keyboard and type something. and hit enter nothing shows up, i have 3 Reasons why this is so irritating. 1. Can't join fun severs like A$$Pixel, Zentic etc. 2. Can't type seeds, i wanna use seeds but i can't cause of the issue that's causing. 3. Can't talk with friends when they join to have fun. That's my reasons. I hope you can fix it, Have a nice day!

**Comment by FlamedDogo99** [comment]
Hi @NoobXD10, thanks for creating an issue. We’ve been having frequent problems with Android devices not supporting various browser standards. If you could edit your post to include device and browser information, such as OS, browser, user agent, and any custom keyboard apps, that would be extremely helpful for diagnosing this problem.

We are currently working on Eagler Mobile v3.1, which will include a custom keyboard for gamepad players. If all else fails, Android users will be able to use that instead of the built in keyboard.

**Comment by EchoEngineer434** [comment]
Thanks that you've replied, but you've replied late. You can close this issue since Volconcium made his own Userscript and typing is now working, so you could close this issue. @FlamedDogo99

**Comment by FlamedDogo99** [comment]
Do you mind linking Volconcium‘s fix? I’ve been reading through the web standards that android supports, and the only way I can see anything working is making a complete custom keyboard.

**Comment by EchoEngineer434** [comment]
It's alright, Volconcium Userscript link: https://github.com/irv77/EaglerPocketMobile/blob/main/demo/eaglerpocketmobile.user.js

**Comment by FlamedDogo99** [comment]
Oh, I didn’t realize that it was just @irv77 ‘s fork. I’m surprised that anything is fixed for you, because his repo is currently just css changes, specifically the background images and screen placement of buttons.
